---
- name: Get RDS endpoint
  rds:
    command: facts
    region: "{{ aws_region }}"
    instance_name: "{{ simplye_role }}-{{ simplye_instance_name }}"
  register: rds

- name: Create new ECS task definition
  ecs_taskdefinition:
    containers:
    - name: circ-deploy
      cpu: 512 
      essential: true
      image: "{{ docker_deploy }}:{{ docker_deploy_tag }}"
      memoryReservation: 256
      portMappings:
      - containerPort: 80
        hostPort: 80
      environment:
      - name: "SIMPLIFIED_DB_TASK"
        value: "{{ db_task }}"
      - name: "SIMPLIFIED_PRODUCTION_DATABASE"
        value: "postgresql://{{ psql_username }}:{{ psql_password }}@{{ rds.instance.endpoint }}:5432/{{ psql_db_name }}"
    - name: circ-scripts
      cpu: 300
      essential: true
      image: "{{ docker_scripts }}:{{ docker_scripts_tag }}"
      memoryReservation: 256
      environment:
      - name: "SIMPLIFIED_PRODUCTION_DATABASE"
        value: "postgresql://{{ psql_username }}:{{ psql_password }}@{{ rds.instance.endpoint }}:5432/{{ psql_db_name }}"
    state: present
    region: "{{ aws_region }}"
    family: "{{ simplye_role }}-{{ simplye_instance_name }}-tdef"
  register: task_def

- name: Create ECS task
  ecs_task:
    region: "{{ aws_region }}"
    cluster: "{{ simplye_role }}-{{ simplye_instance_name }}-ecs"
    operation: run
    task_definition: "{{ simplye_role }}-{{ simplye_instance_name }}-tdef"
    count: 1
    started_by: ansible_user
  register: task_output

- name: Create ECS service
  ecs_service:
    name: "{{ simplye_role }}-{{ simplye_instance_name }}-srv"
    region: "{{ aws_region }}"
    state: present
    cluster: "{{ simplye_role }}-{{ simplye_instance_name }}-ecs"
    desired_count: 1
    task_definition: "{{ simplye_role }}-{{ simplye_instance_name }}-tdef"

- local_action:
    module: ec2
    region: "{{ aws_region }}"
    instance_tags:
      Name: "{{ simplye_role }}-{{ simplye_instance_name }}"
    state: restarted
